### ISSUE TITLE
The Tab key indents an item and navigates to a link panel at the same time

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-list#43] opened 2017-03-18 22:11 UTC
With content like:

```html
<ul>
  <li><a href="xxx">xxx</a></li>
  <li><a href="xxx">xxx</a></li>
</ul>
```

Place the caret in the second item and press <kbd>Tab</kbd>. Both things will happen – the item will be indented and the focus will move to the link panel.

The list feature should stop the event after handling it. In fact... all other features should do the same when handling some key, so we may have more such issues.

**Comment by scofalik** [comment] 2017-03-23 17:56
I guess we need some agreement how to handle this.

This is how <kbd>Tab</kbd> is handled in `List` feature:
https://github.com/ckeditor/ckeditor5-list/blob/master/src/list.js#L60-L79

As you can see, `evt` is stopped. So I guess event priority is the issue. I changed that event priority to `highest` and it did fixed the bug.

However the question is whether I should bump the priority or whether priority of <kbd>Tab</kbd> key in UI should be lower?

**Comment by fredck** [comment] 2017-03-24 09:42
I think that "fallback generic listeners" should have lower priority in general, to give a chance to specific customization to act first. This is the case of the Tab key where the UI behavior is the generic fallback, if nothing else catches it first.

Therefore, I think that the Tab key in the UI should have lower priority, to allow for easier customization inside features.

**Comment by scofalik** [comment] 2017-03-24 10:25
If that's the case, I am closing the issue.

**Closed by scofalik** 2017-03-24 10:25 UTC
Labels: candidate:1.0.0, status:confirmed, type:bug

**Comment by fredck** [comment] 2017-03-24 10:27
Ok, be sure to follow this up in the UI tracker then, otherwise the issue is not resolved.

**Comment by Reinmar** [comment] 2017-03-24 10:29
https://github.com/ckeditor/ckeditor5-link/issues/87 Done. I'll also look for similar situations in ckeditor5-ui and other packages.

**Comment by canvaspixels** [comment] 2019-06-11 09:30
a11y question. Isn't it a problem using the tab key? I mean I guess you shouldn't get trapped in the editor but might it be a nuisance?
