### ISSUE TITLE
Heading and List Plugin are conflicting with each other.

### ISSUE THREAD

**Issue by abhishek6262** [ckeditor/ckeditor5-list#130] opened 2019-07-15 21:03 UTC
CKEditor 5 Heading and List Plugin are conflicting with each other and resulting into an error.

`CKEditorError: "schema-cannot-register-item-twice: A single item cannot be registered twice in the schema. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-schema-cannot-register-item-twice
 {"itemName":"paragraph"}"`

**Comment by Mgsy** [comment] 2019-07-16 07:24
Hello, can you give us more information about your environment and integration (code sample of your config will be appreciated)? Are you using a build or you're building editor from source? Also, please make sure that your packages are updated (you can use [npm-check-updates](https://www.npmjs.com/package/npm-check-updates)).

**Comment by abhishek6262** [comment] 2019-07-23 14:41
We're creating it from the source. We're attaching the package.json file and also the component we've used it in for better reference. Moreover, we're using a windows machine with npm 6.9.0.

Thanks.

[integration.txt](https://github.com/ckeditor/ckeditor5-list/files/3422602/integration.txt)
[package.json.txt](https://github.com/ckeditor/ckeditor5-list/files/3422603/package.json.txt)

**Comment by Mgsy** [comment] 2019-07-25 08:20
I can see that you're using TypeScript in your Vue integration. @oleq, is there a chance that this configuration is messing in our solution?

**Comment by oleq** [comment] 2019-07-29 09:55
[Only the `Paragraph` plugin registers schema for `'paragraph'`](https://github.com/ckeditor/ckeditor5-paragraph/blob/aea609bcce1e67447b2cbfc352e9c6ab6ce68dbb/src/paragraph.js#L40). So if that error shows up, that plugin must've been loaded twice into the editor. The question is: how? 

Both `ListEditing` and `HeadingEditing` require the `Paragraph` plugin but this kind of dependency is resolved by the editor itself and [it throws `plugincollection-plugin-name-conflict` if found one](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-plugincollection-plugin-name-conflict).

Also, if the plugin constructor has already been loaded (or is being loaded), it [should not be loaded again](https://github.com/ckeditor/ckeditor5-core/blob/e79d2abd7a34fa0121ea85476a2af4b92e5608a1/src/plugincollection.js#L209-L211).

So this is weird; this schema collision should never happen. Anyway, what happens if you import `Paragraph` 

```js
import ParagraphPlugin from '@ckeditor/ckeditor5-paragraph/src/paragraph';
```

and add it to `editorConfig.plugins: [ ... ]`?

> I can see that you're using TypeScript in your Vue integration. @oleq, is there a chance that this configuration is messing in our solution?

This should not be an issue.

**Comment by stephanpieterse** [comment] 2019-08-08 10:49
I experienced the exact same behaviour earlier today, while adding the `List` plugin to a custom build.

The "fix" was to delete the node_modules folder, run `npm install` and everything was fine again.

I've been trying for the past hour to replicate the commands I used to get it into the broken state, to no avail. From broken VS working build folder structure, the issue on my side seems to boil down at some stage during the installation of dependencies, `ckeditor5-paragraph` plugin ended up in the node_modules of `ckeditor5-list`, rather than on the same level or higher. Copying or moving the folder there on a clean / working project produces the `schema-cannot-register-item-twice` error consistently, and removing it fixes it.

My versions are quite a bit behind:
{ npm: '3.5.2',
  ares: '1.14.0',
  cldr: '32.0.1',
  http_parser: '2.7.1',
  icu: '60.2',
  modules: '57',
  nghttp2: '1.30.0',
  node: '8.10.0',
  openssl: '1.0.2n',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.18.0',
  v8: '6.2.414.50',
  zlib: '1.2.11' }

Since my versions are quite old I expect that upgrading npm will make sure this doesn't happen again. The workaround is also fairly straightforward, although it probably doesn't help with finding and fixing the cause.

**Closed** 2019-09-03 10:25 UTC
Labels: pending:feedback
