### ISSUE TITLE
List postfixers should always check `type` attribute and type of element.

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-list#103] opened 2018-05-14 14:10 UTC
The `type` attribute has a general name that might be used in other features. One such a feature was [created here](https://github.com/ckeditor/ckeditor5/issues/1010#issue-319168252). Basically it adds a `type` attribute on `video` model element which represents the type of a media, ie `video/mp4`.

Unfortunately using it with conjunction with the `List` features leads to removing `type` attribute from a `video` element by List postfixer:

https://github.com/ckeditor/ckeditor5-list/blob/8074189abd6b406c02edd697556a267b8ae4e053/src/converters.js#L600-L620

The problem is that it should also if `item` is a `listItem` as in other checks.

**Comment by scofalik** [comment] 2018-05-14 19:06
AFAIR without looking at the code, the problem won't be resolved by checking `item.name`. We will need to rename `type` to `listType`.

**Comment by jodator** [comment] 2018-05-15 06:39
@scofalik yeah I'm checking this on schema - if it's allowed then it stays. The problem is that postfixer doesn't know which element it was previously - so it was removing it from every element (even those newly created). The simple check for now which I've added is to check schema.

Also this should be cleaned upon resolving this: https://github.com/ckeditor/ckeditor5-engine/issues/1228.

**Comment by Reinmar** [comment] 2018-05-15 08:00
The problem is deeper. Much deeper. The `type` may be allowed on `<listItem>` and `<video>`. What if someone renames one to another? This postfixer, even when based on the schema (as after ckeditor/ckeditor5-engine#1228), will keep this attribute. The problem is that its value will be invalid in the context of the new element.

This indicates that we should rename this attribute to `listType`. Attributes belonging to specific elements should be prefixed with their names (or made unique in some other way).

Another example – the same situation might occur if `<p alignment>` was renamed to `<image>`. The `<image>` might allow `alignment` and the same situation would occur again. However, `<image>` should not use `alignment` attribute (unless, of course, it's handled by the same feature which handles it on paragraphs). It should use `imageAlignment`. Just like we have `imageStyle` instead of `style` (which was caused by a completely different problem, but turns out to be good :D).

So, I'm ok with renaming `type` to `listType`. We should go further and rename also `listItem`'s `indent` to `listIndent`.

As for the `image`'s `src` and `alt`, we might rename them too unless we want to make an exception for object elements which are never going to be renamed to anything (so their attributes won't leak), but then we have to live with that inconsistent `imageStyle`.

**Comment by Reinmar** [comment] 2018-06-04 11:29
> So, I'm ok with renaming type to listType. We should go further and rename also listItem's indent to listIndent.

@scofalik gave 👍 to that and @pjasiun was fine with this change too. Let's do it, then.

**Closed** 2018-06-13 16:48 UTC
Labels: status:confirmed, type:bug
